version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 11.a, < 12"
  - dependency-name: "@types/node"
    versions:
    - ">= 12.a, < 13"
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
  - dependency-name: "@types/node"
    versions:
    - ">= 9.a, < 10"
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: xmldom
    versions:
    - 0.5.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.16.1
    - 4.17.0
    - 4.18.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.16.1
    - 4.17.0
    - 4.18.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.20.0
    - 7.22.0
  - dependency-name: ts-jest
    versions:
    - 26.5.1
    - 26.5.3
  - dependency-name: semantic-release
    versions:
    - 17.3.9
    - 17.4.1
  - dependency-name: jsdoc-to-markdown
    versions:
    - 7.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
